### ISSUE TITLE
PLEASE ADD BACK SAVE THE WORLD

### ISSUE THREAD

**Issue by Milxnor** [Lawin0129/LawinServerV2#5]

**Comment by Jacobb626** [comment]
goofy ass

**Comment by UWUFN** [comment]
YES

**Comment by FortniteGameServer** [comment]
Idc do whatever

**Comment by PRO100KatYT** [comment]
It would be too much code (and time spent on coding it) since every MCP operation in LawinServerV2 has checks unlike LawinServerV1.
Additionally, from what I've seen, the vast majority of players use the backends only for BR.
I'm not saying that there will never be StW support in V2, but there are currently no plans for that.

**Comment by AntogamerYT** [comment]
It's useless imo, just use lawinserver v1

**Comment by FortniteGameServer** [comment]
Exactly

**Comment by Jyzodev** [comment]
Not completed
